version: '3'
services:
  docker-app:
    image: gomesgeorgelucas/spring-boot-docker-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password