application:
  jwt:
    secretKey:1my2Really3Strong4Key5Repeats#$21my2Really3Strong4Key5Repeats#$21my2Really3Strong4Key5Repeats#$2
    tokenPrefix:Bearer 
    tokenExpirationAfterDays:14

server:
  port: 8080
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: never
    include-exception: false

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: postgres
    password: password
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: false
  main:
    banner-mode: off
  sql:
    init:
      mode: always